version: '3'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=grim
      - MYSQL_USER=ndxbn
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "25672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ndxbn
      - RABBITMQ_DEFAULT_PASS=secret
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOO_STANDALONE_ENABLED=true
      - ZOO_SKIP_ACL=yes
  mialhog:
    image: "mailhog/mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secretkey
    entrypoint:
      - minio
      - server
      - /export

