#!/usr/bin/env zsh
# FAILSAFE
if [[ -f "$HOME/.config/shell/xdg.env.sh" ]]; then
	source "$HOME/.config/shell/xdg.env.sh"
fi

## History Settings
HISTSIZE=1000000000
SAVEHIST=1000000000
HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/zsh_history"
[[ -d "$(dirname "$HISTFILE")" ]] || mkdir -p "$(dirname "$HISTFILE")"

# My Plugin Manager
_ZPLUGIN_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins"
mkdir -p ${_ZPLUGIN_DIR}
function zload() {
	local repo="$1"
	local plugin_name="${repo:t}"
	local plugin_dir="${_ZPLUGIN_DIR}/${plugin_name}"

	# download plugin package
	if [[ ! -d "$plugin_dir" ]]; then
		git clone --depth 1 --recursive "https://github.com/${repo}.git" "$plugin_dir"
	fi

	# you must add fpath before `compinit`
	fpath=("${plugin_dir}" $fpath)

	# if plugin has any constructor script, import it.
	if [[ -f "${plugin_dir}/${plugin_name}" ]]; then # e.g. "arzzen/calc.plugin.zsh"
		source "${plugin_dir}/${plugin_name}"
	elif [[ -f "$plugin_dir/${plugin_name}.plugin.zsh" ]]; then # e.g. "chrissicool/zsh-256color"
		source "$plugin_dir/${plugin_name}.plugin.zsh"
	elif [[ -f "$plugin_dir/${plugin_name}.zsh" ]]; then # legacy package
		source "$plugin_dir/${plugin_name}.zsh"
	fi
}
function zupdate() {
	find "$_ZPLUGIN_DIR" -mindepth 1 -maxdepth 1 -type d | while read -r dir; do
		git -C "$dir" pull
	done
}

# Completions
zload "zsh-users/zsh-completions"
if [[ -d "${_ZPLUGIN_DIR}/zsh-completions/src" ]]; then
	fpath=("${_ZPLUGIN_DIR}/zsh-completions/src" $fpath)
fi
fpath=("${XDG_DATA_HOME:-$HOME/.local/share}/zsh/site-functions" $fpath)
autoload -Uz compinit && compinit
autoload -Uz bashcompinit && bashcompinit

# Prompt Theme
autoload -Uz promptinit && promptinit
prompt ndxbn

# Local Plugins
for config in "${_ZPLUGIN_DIR}/_local/"*.zsh(N); do
	[[ -f "$config" ]] && source "$config"
done

# External Plugins
zload "zsh-users/zsh-autosuggestions"
zload "chrissicool/zsh-256color"

## The official zsh-syntax-highlighting documentation requires sourcing it at the end of ".zshrc"
##   because it installs ZLE hooks and wraps ZLE widgets.
zload "zsh-users/zsh-syntax-highlighting"
